# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o main ."
  bin = "main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  stop_on_error = true

[log]
  time = true

[color]
  main = "yellow"
